### ISSUE TITLE
Mirage not working only for me. Here is console error that pops up when enemies try to speak

### ISSUE THREAD

**Issue by OdysseyAi** [qwbarch/mirage#102]
Mirage is working for everyone with modpack except me, when I'm hosting lobby Mirage not working with everyone
![image](https://github.com/user-attachments/assets/af015da9-96de-4272-be80-b5afb83e1c79)

**Comment by qwbarch** [comment]
Sorry for the late response. I'm currently looking into this issue, but honestly I don't know when this'll be fixed as of right now

**Comment by qwbarch** [comment]
Hello, can you try to see if [MirageExperimental v0.0.44](<https://thunderstore.io/c/lethal-company/p/qwbarch/MirageExperimental/>) fixes the issue for you?

**Comment by OdysseyAi** [comment]
> Hello, can you try to see if [MirageExperimental v0.0.44](https://thunderstore.io/c/lethal-company/p/qwbarch/MirageExperimental/) fixes the issue for you?

Issue is still present with MirageExperimental
![image](https://github.com/user-attachments/assets/442a062f-6104-4a75-9e35-cdb4074a6710)

**Comment by qwbarch** [comment]
Thanks for testing. That's unfortunate, I have one other thing in mind that might fix it that I'll work on in the meantime

**Comment by qwbarch** [comment]
Can you try [MirageExperimental v0.0.45](<https://thunderstore.io/c/lethal-company/p/qwbarch/MirageExperimental/versions/>)? Hopefully it's fixed this time

**Comment by OdysseyAi** [comment]
> Can you try [MirageExperimental v0.0.45](https://thunderstore.io/c/lethal-company/p/qwbarch/MirageExperimental/versions/)? Hopefully it's fixed this time
> 
> Edit: I forgot to mention, this specific version changes it to save/read as an mp3 rather than a wav, so if you have the setting to never delete recordings, you'll have to delete the recordings folder since i forgot to add a runtime check for it

Everything works on v0.0.45! Thank you for fixing the issue. So now I need to use experimental version while my friends use regular Mirage, right?
Oh and btw, this PlayerOneShot null AudioClip message spams in console all the time, is this normal?
![image](https://github.com/user-attachments/assets/5b582161-c08d-4500-afed-e720786e1da6)

**Comment by qwbarch** [comment]
The ``PlayOneShot`` warning is from the vanilla game IIRC, if not then it's from another mod. Mirage never calls that method at all.

For now you'll need to run ``MirageExperimental`` until I push it to ``Mirage`` itself, I'm still doing some tests before I push an official update.

Glad it finally works now!

**Comment by qwbarch** [comment]
Fixed in ``Mirage v1.12.0``. Thanks for the bug report and for testing
